### Health check

GET http://localhost:3000/health HTTP/1.1

### Get Projects
GET http://localhost:3000/v1/projects HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlBmZ25aWFBwU2tJQWR2VllUd2JvSiJ9.eyJpc3MiOiJodHRwczovL2Rldi14c3VzYXVnZGF3enNrZGtlLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDExNjgzNDU2MTMwMDkyMjMyNTc2NyIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYteHN1c2F1Z2Rhd3pza2RrZS51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzU3OTQxNTQ0LCJleHAiOjE3NTc5NDg3NDQsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiZzRKMXdnOHU2d1N3NkFscnVVeXZ5MURnOFJLdlYxdGYifQ.PZUaVQ3RzPwmFjDfswEiMQJsBcNXzpvNYKrElB2J7D9rluI2JU0LO16rpK4KrdIpJN6cSjfeCHyLvNfGZq-m4bI6JdsCHJ8rEaa5P8ggjk_M09y5jxP0jmLtpD_iuoz02ujftZjH5HAjRGqvIywJUJTsw7tnd07QXDYV5FHsgk84xks5rKJTTySCSE_4kTPw5vYY9t0n23CVB8RE7WLILgSHlPvpLMAmFXM7f4KIABmyiP23vlL2LNfrLjzwM8PjWUGpIgWMqZGyk9uBK8FuBtRk0hyCh8vDVtrx4ZE4V5ERvjV2EdNfZQeT6HfQ20PegsBka4dzJaqd1l_mipnJEw

### GET task`s
GET http://localhost:3000/v1/tasks?search=task&completed=0&orderBy=created_at-desc HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlBmZ25aWFBwU2tJQWR2VllUd2JvSiJ9.eyJpc3MiOiJodHRwczovL2Rldi14c3VzYXVnZGF3enNrZGtlLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDExNjgzNDU2MTMwMDkyMjMyNTc2NyIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYteHN1c2F1Z2Rhd3pza2RrZS51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzU3OTQxNTQ0LCJleHAiOjE3NTc5NDg3NDQsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiZzRKMXdnOHU2d1N3NkFscnVVeXZ5MURnOFJLdlYxdGYifQ.PZUaVQ3RzPwmFjDfswEiMQJsBcNXzpvNYKrElB2J7D9rluI2JU0LO16rpK4KrdIpJN6cSjfeCHyLvNfGZq-m4bI6JdsCHJ8rEaa5P8ggjk_M09y5jxP0jmLtpD_iuoz02ujftZjH5HAjRGqvIywJUJTsw7tnd07QXDYV5FHsgk84xks5rKJTTySCSE_4kTPw5vYY9t0n23CVB8RE7WLILgSHlPvpLMAmFXM7f4KIABmyiP23vlL2LNfrLjzwM8PjWUGpIgWMqZGyk9uBK8FuBtRk0hyCh8vDVtrx4ZE4V5ERvjV2EdNfZQeT6HfQ20PegsBka4dzJaqd1l_mipnJEw

### GET task by ID
GET http://localhost:3000/v1/tasks/cm5fm8t1z0001840lc1070727 HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlBmZ25aWFBwU2tJQWR2VllUd2JvSiJ9.eyJpc3MiOiJodHRwczovL2Rldi14c3VzYXVnZGF3enNrZGtlLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDExNjgzNDU2MTMwMDkyMjMyNTc2NyIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYteHN1c2F1Z2Rhd3pza2RrZS51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzU3OTQxNTQ0LCJleHAiOjE3NTc5NDg3NDQsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiZzRKMXdnOHU2d1N3NkFscnVVeXZ5MURnOFJLdlYxdGYifQ.PZUaVQ3RzPwmFjDfswEiMQJsBcNXzpvNYKrElB2J7D9rluI2JU0LO16rpK4KrdIpJN6cSjfeCHyLvNfGZq-m4bI6JdsCHJ8rEaa5P8ggjk_M09y5jxP0jmLtpD_iuoz02ujftZjH5HAjRGqvIywJUJTsw7tnd07QXDYV5FHsgk84xks5rKJTTySCSE_4kTPw5vYY9t0n23CVB8RE7WLILgSHlPvpLMAmFXM7f4KIABmyiP23vlL2LNfrLjzwM8PjWUGpIgWMqZGyk9uBK8FuBtRk0hyCh8vDVtrx4ZE4V5ERvjV2EdNfZQeT6HfQ20PegsBka4dzJaqd1l_mipnJEw

### Create task
GET http://localhost:3000/v1/tasks HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZZRDhLdEpfdzBZTWttQXZhVUlNSiJ9.eyJpc3MiOiJodHRwczovL2Rldi1ubHl5ZHhwdGNwZWxoNTNuLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDU0MTY2NzczNTg2OTkyMzc1OSIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtbmx5eWR4cHRjcGVsaDUzbi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzQwMjQwNTUxLCJleHAiOjE3NDAyNDc3NTEsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiS3RaMHBPcHBqRkRaUG1xOE9lR21vSE1VZTRxdG1ROUEifQ.QsYnmrrwb2PLqpZl7-llxyGg3QeD9kZpU71qhhKAjlmRzeOHQuoB7cSIVp_03lj8gAsE7Ty09bvHheu7-ZCBfoji1VWeQkRe_4rXK_XrKSm9lQASSCWGVz5URDEK5R4tsasnIv8QMNy-aFVbta7NA0BpCt0MyCDd7yM5f9zaKLb9WYNAbuw0vRb8wv4rkJty_F6PloCANyvAGN1VaF0o_xdLN4nD6wt6oqyEpphSCCbckKGZMp7wYmmzKk9zxd7tmVF3V3DyvRBMXutSDLW5zWDX-tplz1EikGEVFKXanaSqGerVV9zcHC4xTGbrzJrI2j3FiVb2LOXCiooGtfpG1A

{
    "name": "Implement Strategy Pattern"
}

### Mark Task as Complete
PATCH http://localhost:3000/v1/tasks/cm6cm4bm500018jych8pkz0s2/complete
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlBmZ25aWFBwU2tJQWR2VllUd2JvSiJ9.eyJpc3MiOiJodHRwczovL2Rldi14c3VzYXVnZGF3enNrZGtlLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDExNjgzNDU2MTMwMDkyMjMyNTc2NyIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYteHN1c2F1Z2Rhd3pza2RrZS51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzU3OTQxNTQ0LCJleHAiOjE3NTc5NDg3NDQsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiZzRKMXdnOHU2d1N3NkFscnVVeXZ5MURnOFJLdlYxdGYifQ.PZUaVQ3RzPwmFjDfswEiMQJsBcNXzpvNYKrElB2J7D9rluI2JU0LO16rpK4KrdIpJN6cSjfeCHyLvNfGZq-m4bI6JdsCHJ8rEaa5P8ggjk_M09y5jxP0jmLtpD_iuoz02ujftZjH5HAjRGqvIywJUJTsw7tnd07QXDYV5FHsgk84xks5rKJTTySCSE_4kTPw5vYY9t0n23CVB8RE7WLILgSHlPvpLMAmFXM7f4KIABmyiP23vlL2LNfrLjzwM8PjWUGpIgWMqZGyk9uBK8FuBtRk0hyCh8vDVtrx4ZE4V5ERvjV2EdNfZQeT6HfQ20PegsBka4dzJaqd1l_mipnJEw

### GET projects
GET http://localhost:3000/v1/projects HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlBmZ25aWFBwU2tJQWR2VllUd2JvSiJ9.eyJpc3MiOiJodHRwczovL2Rldi14c3VzYXVnZGF3enNrZGtlLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDExNjgzNDU2MTMwMDkyMjMyNTc2NyIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYteHN1c2F1Z2Rhd3pza2RrZS51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzU3OTQxNTQ0LCJleHAiOjE3NTc5NDg3NDQsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiZzRKMXdnOHU2d1N3NkFscnVVeXZ5MURnOFJLdlYxdGYifQ.PZUaVQ3RzPwmFjDfswEiMQJsBcNXzpvNYKrElB2J7D9rluI2JU0LO16rpK4KrdIpJN6cSjfeCHyLvNfGZq-m4bI6JdsCHJ8rEaa5P8ggjk_M09y5jxP0jmLtpD_iuoz02ujftZjH5HAjRGqvIywJUJTsw7tnd07QXDYV5FHsgk84xks5rKJTTySCSE_4kTPw5vYY9t0n23CVB8RE7WLILgSHlPvpLMAmFXM7f4KIABmyiP23vlL2LNfrLjzwM8PjWUGpIgWMqZGyk9uBK8FuBtRk0hyCh8vDVtrx4ZE4V5ERvjV2EdNfZQeT6HfQ20PegsBka4dzJaqd1l_mipnJEw

### GET project by ID
GET http://localhost:3000/v1/projects/cmfjl5pwv0000xw5h58oer6oi HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlBmZ25aWFBwU2tJQWR2VllUd2JvSiJ9.eyJpc3MiOiJodHRwczovL2Rldi14c3VzYXVnZGF3enNrZGtlLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDExNjgzNDU2MTMwMDkyMjMyNTc2NyIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYteHN1c2F1Z2Rhd3pza2RrZS51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzU3OTQxNTQ0LCJleHAiOjE3NTc5NDg3NDQsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiZzRKMXdnOHU2d1N3NkFscnVVeXZ5MURnOFJLdlYxdGYifQ.PZUaVQ3RzPwmFjDfswEiMQJsBcNXzpvNYKrElB2J7D9rluI2JU0LO16rpK4KrdIpJN6cSjfeCHyLvNfGZq-m4bI6JdsCHJ8rEaa5P8ggjk_M09y5jxP0jmLtpD_iuoz02ujftZjH5HAjRGqvIywJUJTsw7tnd07QXDYV5FHsgk84xks5rKJTTySCSE_4kTPw5vYY9t0n23CVB8RE7WLILgSHlPvpLMAmFXM7f4KIABmyiP23vlL2LNfrLjzwM8PjWUGpIgWMqZGyk9uBK8FuBtRk0hyCh8vDVtrx4ZE4V5ERvjV2EdNfZQeT6HfQ20PegsBka4dzJaqd1l_mipnJEw
### GET project's tasks
GET http://localhost:3000/v1/projects/1/tasks HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlBmZ25aWFBwU2tJQWR2VllUd2JvSiJ9.eyJpc3MiOiJodHRwczovL2Rldi14c3VzYXVnZGF3enNrZGtlLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDExNjgzNDU2MTMwMDkyMjMyNTc2NyIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYteHN1c2F1Z2Rhd3pza2RrZS51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzU3OTQxNTQ0LCJleHAiOjE3NTc5NDg3NDQsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiZzRKMXdnOHU2d1N3NkFscnVVeXZ5MURnOFJLdlYxdGYifQ.PZUaVQ3RzPwmFjDfswEiMQJsBcNXzpvNYKrElB2J7D9rluI2JU0LO16rpK4KrdIpJN6cSjfeCHyLvNfGZq-m4bI6JdsCHJ8rEaa5P8ggjk_M09y5jxP0jmLtpD_iuoz02ujftZjH5HAjRGqvIywJUJTsw7tnd07QXDYV5FHsgk84xks5rKJTTySCSE_4kTPw5vYY9t0n23CVB8RE7WLILgSHlPvpLMAmFXM7f4KIABmyiP23vlL2LNfrLjzwM8PjWUGpIgWMqZGyk9uBK8FuBtRk0hyCh8vDVtrx4ZE4V5ERvjV2EdNfZQeT6HfQ20PegsBka4dzJaqd1l_mipnJEw